{
    "aircraft": "data/meta-dataset/fgvc-aircraft-2013b/data",
    "ChestX": "data/meta-dataset/ChestX/data",
    "clipart": "data/meta-dataset/clipart",
    "coco": "data/meta-dataset/coco",
    "cub": "data/meta-dataset/cub",
    "EuroSAT": "data/meta-dataset/EuroSAT",
    "fungi": "data/meta-dataset/fungi_train_val/images",
    "GTSRB": "data/meta-dataset/GTSRB/Final_Training/Images",
    "infograph": "data/meta-dataset/infograph",
    "ISIC": "data/meta-dataset/ISIC",
    "omniglot": "data/meta-dataset/omniglot",
    "PlantDisease": "data/meta-dataset/PlantDisease",
    "quickdraw": "data/meta-dataset/quickdraw",
    "real": "data/meta-dataset/real",
    "sketch": "data/meta-dataset/sketch",
    "omniglot": "data/meta-dataset/omniglot",
    "Textures": "data/meta-dataset/Textures/dtd/images",
    "vggflower": "data/meta-dataset/VGGFlower",
    "miniImageNet": "data/mini_imagenet/mini-imagenet",
}
